baseurl = "/"
languageCode = "en-us"
title = "izaron"
folder = "/home/izaron"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "Open-Source | [Github](https://github.com/izaron)"
    custom_css = ["css/theme-override.css"]
